//go:build swagger

package server

import (
	"github.com/gin-gonic/gin"
	swaggerfiles "github.com/swaggo/files"
	ginswagger "github.com/swaggo/gin-swagger"

	// docs is generated by `swag init` (see the Makefile `swagger` target) and
	// committed so the `-tags swagger` build is self-contained.
	_ "github.com/zhaochy1990/auth-service/cmd/auth-service/docs"
)

// mountSwagger serves the Swagger UI at /swagger/*any when enabled. Compiled
// only with `-tags swagger`, which requires the generated
// cmd/auth-service/docs package.
func mountSwagger(r *gin.Engine, enabled bool) {
	if !enabled {
		return
	}
	r.GET("/swagger/*any", ginswagger.WrapHandler(swaggerfiles.Handler))
}
